config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  # # CREATE
  get "task/new", to: "tasks#new", as: "new_task" # page form
  post "tasks", to: "tasks#create" # url receive data from form

  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  delete 'tasks/:id', to: 'tasks#destroy'

  patch 'tasks/:id', to: 'tasks#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new(set_params)
    @task.save
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id]) # a commenter avec le before_action
  end


  def new
    @task = Task.new
  end

  private

  def set_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1> Our first Task </h1>

<% @tasks.each do |task| %>
<%# <%= task.title %>
<%= link_to task.title, task_path(task)%>
<% end %>

<button>
<%= link_to "Create a new task", new_task_path %>
</button>

app/views/tasks/new.html.erb
<h4> My new task </h4>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

<%#= render "form", restaurant: @restaurant %>

app/views/tasks/show.html.erb
<h2> <%= @task.title %> </h2>
<p> <%= @task.details %> </p>
<p> <%= @task.completed %> </p>

<%= link_to "Back to the Future", tasks_path  %>